
CREATE USER user_name WITH password 'user_password';
ALTER ROLE role_name WITH SUPERUSER, CREATEROLE, CREATEDB, REPLICATION, BYPASSRLS;
CREATE DATABASE nombre_db WITH OWNER nombre_usuario;
CREATE DATABASE Ratatouille WITH OWNER dfom89;