export const FILTER_BY_DIETS = "FILTER_BY_DIETS";
export const FILTER_BY_FIELD = "FILTER_BY_FIELD";
export const FILTER_BY_NAME = "FILTER_BY_NAME";
export const FILTER_BY_ORDER = "FILTER_BY_ORDER";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";