export const ADD_NEW_RECIPE = "ADD_NEW_RECIPE";
export const CLEAN_RECIPE_DETAIL = "CLEAN_RECIPE_DETAIL";
export const CREATE_RECIPE = "CREATE_RECIPE";
export const REMOVE_RECIPE = "REMOVE_RECIPE";
export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID'
export const GET_RECIPE_DETAIL = 'GET_RECIPES_DETAIL'